In [66]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
pd.set_option("max_columns",None)

In [2]:
# load the dataset created by the songs-data-processyng.ipynb to avoid
full_tracks = pd.read_csv('full_tracks.csv')
#full_tracks.shape
full_tracks.head()

track_id   album_date_created  yt_views  genre_Experimental  \
0         3  2008-11-26 01:44:45    1936.0                   0   
1         5  2008-11-26 01:44:45   87392.0                   0   
2        10  2008-11-26 01:45:08  193927.0                   0   
3        20  2008-11-26 01:45:05  100282.0                   0   
4        26  2008-11-26 01:45:05  201490.0                   0   

   genre_Electronic  genre_Rock  genre_Instrumental  genre_Pop  genre_Folk  \
0                 0           0                   0          0           0   
1                 0           0                   0          0           0   
2                 0           0                   0          1           0   
3                 0           0                   0          1           1   
4                 0           0                   0          1           1   

   genre_Punk  genre_Avant-Garde  genre_Hip-Hop  genre_Noise  track_id.1  \
0           0                  0              1            0           3   
1           0                  0              1            0           5   
2           0                  0              0            0          10   
3           0                  0              0            0          20   
4           0                  0              0            0          26   

   chroma_cens_kurtosis_1  chroma_cens_kurtosis_2  chroma_cens_kurtosis_3  \
0                1.888963                0.760539                0.345297   
1                0.527563               -0.077654               -0.279610   
2                3.702245               -0.291193                2.196742   
3               -0.193837               -0.198527                0.201546   
4               -0.699535               -0.684158                0.048825   

   chroma_cens_kurtosis_4  chroma_cens_kurtosis_5  chroma_cens_kurtosis_6  \
0                2.295201                1.654031                0.067592   
1                0.685883                1.937570                0.880839   
2               -0.234449                1.367364                0.998411   
3                0.258556                0.775204                0.084794   
4                0.042659               -0.818967               -0.917123   

   chroma_cens_kurtosis_7  chroma_cens_kurtosis_8  chroma_cens_kurtosis_9  \
0                1.366848                1.054094                0.108103   
1               -0.923192               -0.927232                0.666617   
2                1.770694                1.604566                0.521217   
3               -0.289294               -0.816410                0.043851   
4               -0.901834               -0.066845               -0.291037   

   chroma_cens_kurtosis_10  chroma_cens_kurtosis_11  chroma_cens_kurtosis_12  \
0                 0.619185                 1.038253                 1.292235   
1                 1.038546                 0.268932                 1.125141   
2                 1.982386                 4.326824                 1.300406   
3                -0.804761                -0.990958                -0.430381   
4                -0.861782                -0.670444                -0.994519   

   chroma_cens_max_1  chroma_cens_max_2  chroma_cens_max_3  chroma_cens_max_4  \
0           0.677641           0.584248           0.581271           0.581182   
1           0.611014           0.651471           0.494528           0.448799   
2           0.461840           0.540411           0.446708           0.647553   
3           0.652864           0.676290           0.670288           0.598666   
4           0.698460           0.568883           0.612372           0.663034   

   chroma_cens_max_5  chroma_cens_max_6  chroma_cens_max_7  chroma_cens_max_8  \
0           0.454241           0.464841           0.542833           0.664720   
1           0.468624           0.454021           0.497172           0.559755   
2           0.591908           0.513306           0.651501           0.516887   

In [3]:
full_tracks = full_tracks.drop('track_id.1', axis=1)

In [4]:
full_tracks = full_tracks.sort_values('album_date_created')

In [5]:
# Add classification attribute. A song is popular if its views are beyond 10 million.
full_tracks['popular'] = full_tracks.apply(lambda row: 1 if row['yt_views'] > 10000000 else 0, axis=1)

In [6]:
# Selecting the subset of columns to test the CNN 

subset = full_tracks.filter(regex='spectral_contrast|popular', axis=1)

display(subset.head())

display(len(subset.columns))

spectral_contrast_kurtosis_1  spectral_contrast_kurtosis_2  \
0                          3.208793                      0.243778   
1                          1.478091                      0.357150   
2803                       2.280760                      0.097152   
8                          1.834740                      0.719801   
11918                      0.846345                     -0.185002   

       spectral_contrast_kurtosis_3  spectral_contrast_kurtosis_4  \
0                         -0.010697                     -0.281420   
1                          0.455044                      0.075880   
2803                       0.624267                      0.159637   
8                          0.652169                      0.351887   
11918                     -0.238102                     -0.161051   

       spectral_contrast_kurtosis_5  spectral_contrast_kurtosis_6  \
0                          0.251526                      1.278046   
1                         -0.110072                      0.770549   
2803                       0.561057                      2.351403   
8                          0.370726                      0.311464   
11918                      1.436764                     -0.291363   

       spectral_contrast_kurtosis_7  spectral_contrast_max_1  \
0                          3.732807                59.697681   
1                          0.933812                50.931419   
2803                       2.231685                55.784954   
8                          0.606217                51.696037   
11918                     -0.875137                49.593319   

       spectral_contrast_max_2  spectral_contrast_max_3  \
0                    40.604237                42.141411   
1                    38.541519                39.017235   
2803                 37.386108                39.747211   
8                    42.660988                41.526760   
11918                43.066273                42.587910   

       spectral_contrast_max_4  spectral_contrast_max_5  \
0                    31.473713                38.779331   
1                    33.707951                32.751514   
2803                 36.883224                38.202618   
8                    32.224319                42.536064   
11918                36.316479                33.517727   

       spectral_contrast_max_6  spectral_contrast_max_7  \
0                    37.237942                58.204182   
1                    38.786518                51.896751   
2803                 35.145477                56.263454   
8                    34.212406                54.038242   
11918                32.922852                46.781120   

       spectral_contrast_mean_1  spectral_contrast_mean_2  \
0                     15.732023                 15.046037   
1                     17.097452                 15.969444   
2803                  18.151035                 16.300024   
8                     17.004141                 15.552999   
11918                 19.737345                 18.829165   

       spectral_contrast_mean_3  spectral_contrast_mean_4  \
0                     17.374632                 17.210331   
1                     18.646988                 16.973648   
2803                  16.887423                 16.940413   
8                     16.775951                 16.641981   
11918                 19.455009                 17.377213   

       spectral_contrast_mean_5  spectral_contrast_mean_6  \
0                     18.180691                 18.898478   
1                     17.292145                 19.255819   
2803                  17.615170                 16.882601   
8                     18.738556                 18.636620   
11918                 16.683224                 19.947102   

       spectral_contrast_mean_7  spectral_contrast_median_1  \
0                     39.201202                   15.306031   
1                     36.413609                   16.489166   
2803                  

50

In [7]:
X1 = subset.drop(columns='popular')
Y1 = subset['popular']

y_dim = len(X1.columns)

# Split datasets to multiple parts for training, validation and test purposes. 
nb_samples = len(subset)
valid_split = 0.2
test_split = 0.2
X1_train = X1[0:int(nb_samples*(1-valid_split-test_split))]
Y1_train = Y1[0:int(nb_samples*(1-valid_split-test_split))]
X1_valid = X1[int(nb_samples*(1-valid_split-test_split)):int(nb_samples*(1-test_split))]
Y1_valid = Y1[int(nb_samples*(1-valid_split-test_split)):int(nb_samples*(1-test_split))]
X1_test  = X1[int(nb_samples*(1-test_split)):]
Y1_test  = Y1[int(nb_samples*(1-test_split)):]

In [8]:
display(X1_train.shape)
display(X1_valid.shape)
display(X1_test.shape)

(24391, 49)

(8130, 49)

(8131, 49)

In [9]:
from sklearn.preprocessing import StandardScaler

# Use standard scaler to standardize features by removing the mean and scaling to unit variance.

scaler = StandardScaler().fit(X1_train)

X1_train = scaler.transform(X1_train)
X1_valid = scaler.transform(X1_valid)
X1_test  = scaler.transform(X1_test)

# Needed to reshape the 1D arrays to 2D arrays.

Y1_train = Y1_train.values.reshape(-1, 1)
Y1_valid = Y1_valid.values.reshape(-1, 1)
Y1_test = Y1_test.values.reshape(-1, 1)

In [10]:
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.optimizers import SGD, Adam

# Set random seeds.
np.random.seed(1)
from tensorflow import set_random_seed
set_random_seed(2)

from keras import regularizers

col_num = len(subset.columns) - 1

/home/robert/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [11]:
from keras.models import Sequential
from keras.layers.core import Activation, Dense, Flatten
from keras.optimizers import SGD
import matplotlib.pyplot as plt
from keras.layers.convolutional import  Conv1D, MaxPooling1D

In [12]:
# Create the CNN here
model = Sequential()
model.add(Conv1D(filters=32, kernel_size=10, input_shape=(y_dim, 1)))
model.add(MaxPooling1D(pool_size=5 ))
model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='relu'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1 (Conv1D)            (None, 40, 32)            352       
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 8, 32)             0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 256)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 64)                16448     
_________________________________________________________________
dense_2 (Dense)              (None, 32)                2080      
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 33        
Total params: 18,913
Trainable params: 18,913
Non-trainable params: 0
_________________________________________________________________


In [13]:
# Need to resize the input data because the input shape of Keres Conv1D expects 3d
# (number of the data, lenght of the data, channels of the data)
X1_train = X1_train.reshape(24391, y_dim, 1)
X1_valid = X1_valid.reshape(8130, y_dim, 1)
X1_test = X1_test.reshape(8131, y_dim, 1)

In [14]:
model.fit(X1_train, Y1_train, epochs=10, batch_size=12, validation_data=(X1_valid, Y1_valid), verbose=2)

Train on 24391 samples, validate on 8130 samples
Epoch 1/10
 - 5s - loss: 2.0485 - acc: 0.8720 - val_loss: 2.0063 - val_acc: 0.8755
Epoch 2/10
 - 4s - loss: 2.0604 - acc: 0.8722 - val_loss: 2.0063 - val_acc: 0.8755
Epoch 3/10
 - 4s - loss: 2.0604 - acc: 0.8722 - val_loss: 2.0063 - val_acc: 0.8755
Epoch 4/10
 - 4s - loss: 2.0604 - acc: 0.8722 - val_loss: 2.0063 - val_acc: 0.8755
Epoch 5/10
 - 4s - loss: 2.0604 - acc: 0.8722 - val_loss: 2.0063 - val_acc: 0.8755
Epoch 6/10
 - 4s - loss: 2.0604 - acc: 0.8722 - val_loss: 2.0063 - val_acc: 0.8755
Epoch 7/10
 - 4s - loss: 2.0604 - acc: 0.8722 - val_loss: 2.0063 - val_acc: 0.8755
Epoch 8/10
 - 4s - loss: 2.0604 - acc: 0.8722 - val_loss: 2.0063 - val_acc: 0.8755
Epoch 9/10
 - 4s - loss: 2.0604 - acc: 0.8722 - val_loss: 2.0063 - val_acc: 0.8755
Epoch 10/10
 - 4s - loss: 2.0604 - acc: 0.8722 - val_loss: 2.0063 - val_acc: 0.8755


In [15]:
res = model.evaluate(X1_test, Y1_test)
display(res)

8131/8131 [==============================] - 0s 25us/step


[2.026278763702262, 0.874185217070471]

In [16]:
Y1_test.shape

(8131, 1)

In [31]:
X1_test.shape

(8131, 49, 1)

In [29]:
X1_test[0,:]

array([[-1.08193639],
       [-0.04047333],
       [-0.7238686 ],
       [ 1.26342417],
       [-0.69405002],
       [-0.03553693],
       [ 2.12661729],
       [-0.05878678],
       [ 3.60183284],
       [ 2.46406174],
       [ 4.24069965],
       [ 2.09515041],
       [-0.56326352],
       [-1.67696176],
       [ 0.66587966],
       [ 1.60334347],
       [ 1.52990151],
       [ 1.82278251],
       [ 1.80011579],
       [-1.08319504],
       [-2.27200439],
       [ 0.65040531],
       [ 1.03784244],
       [ 1.25443256],
       [ 1.3421882 ],
       [ 1.87065757],
       [-1.32300393],
       [-2.11864865],
       [ 0.4057661 ],
       [ 1.32111787],
       [ 0.99184815],
       [ 0.91363384],
       [ 0.75040377],
       [-0.05216162],
       [ 0.35782393],
       [-0.79516833],
       [ 1.37108656],
       [ 0.14858891],
       [ 1.98601766],
       [-0.26946894],
       [ 1.099261  ],
       [ 1.9323637 ],
       [ 1.86124108],
       [ 4.79405998],
       [ 2.8648618 ],
       [ 4

In [54]:
# check by single values
elem1 = 10
elem2 = 20
res = model.predict(X1_test[elem1:elem2,:].reshape((elem2-elem1),49,1))
display(Y1_test[elem1:elem2])
display(res)

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [51]:
X1_test[elem1:elem2,:]

array([[[-1.08193639e+00],
        [-4.04733329e-02],
        [-7.23868597e-01],
        [ 1.26342417e+00],
        [-6.94050023e-01],
        [-3.55369317e-02],
        [ 2.12661729e+00],
        [-5.87867790e-02],
        [ 3.60183284e+00],
        [ 2.46406174e+00],
        [ 4.24069965e+00],
        [ 2.09515041e+00],
        [-5.63263521e-01],
        [-1.67696176e+00],
        [ 6.65879658e-01],
        [ 1.60334347e+00],
        [ 1.52990151e+00],
        [ 1.82278251e+00],
        [ 1.80011579e+00],
        [-1.08319504e+00],
        [-2.27200439e+00],
        [ 6.50405311e-01],
        [ 1.03784244e+00],
        [ 1.25443256e+00],
        [ 1.34218820e+00],
        [ 1.87065757e+00],
        [-1.32300393e+00],
        [-2.11864865e+00],
        [ 4.05766096e-01],
        [ 1.32111787e+00],
        [ 9.91848154e-01],
        [ 9.13633845e-01],
        [ 7.50403769e-01],
        [-5.21616165e-02],
        [ 3.57823927e-01],
        [-7.95168329e-01],
        [ 1.37108656e+00],
 

In [55]:
res = model.predict(X1_test)

In [57]:
sum(res)

array([0.05084468], dtype=float32)

In [58]:
res

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [59]:
sum(Y1_test)

array([1023])

In [62]:
Y1_test.shape

(8131, 1)

In [65]:
sum(Y1_valid)

array([1012])

In [64]:
Y1_train.shape

(24391, 1)